name: Trigger auto deployment for container-app-yi36oed7pab3q

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-yi36oed7pab3q-AutoDeployTrigger-18d30a23-8c54-48ab-b850-6d18fe33b538.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPYI36OED7PAB3Q_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPYI36OED7PAB3Q_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPYI36OED7PAB3Q_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryyi36oed7pab3q.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPYI36OED7PAB3Q_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPYI36OED7PAB3Q_REGISTRY_PASSWORD }}
          containerAppName: container-app-yi36oed7pab3q
          resourceGroup: expresshello8dca96e7
          imageToBuild: containerregistryyi36oed7pab3q.azurecr.io/container-app-yi36oed7pab3q:${{ github.sha }}
          


