name: Trigger auto deployment for container-app-6ihvmwooxwj34

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-6ihvmwooxwj34-AutoDeployTrigger-9319b8bc-87a7-48e2-a475-b9a689318127.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP6IHVMWOOXWJ34_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP6IHVMWOOXWJ34_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP6IHVMWOOXWJ34_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry6ihvmwooxwj34.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP6IHVMWOOXWJ34_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP6IHVMWOOXWJ34_REGISTRY_PASSWORD }}
          containerAppName: container-app-6ihvmwooxwj34
          resourceGroup: expresshello8dca8a6a
          imageToBuild: containerregistry6ihvmwooxwj34.azurecr.io/container-app-6ihvmwooxwj34:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


