name: Trigger auto deployment for container-app-m6dxzm2q26ey2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-m6dxzm2q26ey2-AutoDeployTrigger-1cb279dc-e1c8-4eef-b096-461cc96284f3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPM6DXZM2Q26EY2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPM6DXZM2Q26EY2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPM6DXZM2Q26EY2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrym6dxzm2q26ey2.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPM6DXZM2Q26EY2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPM6DXZM2Q26EY2_REGISTRY_PASSWORD }}
          containerAppName: container-app-m6dxzm2q26ey2
          resourceGroup: expresshello8dca8226
          imageToBuild: containerregistrym6dxzm2q26ey2.azurecr.io/container-app-m6dxzm2q26ey2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


